# Dependencies
markdown:            kramdown
highlighter:         rouge
gems:                [jekyll-paginate]
encoding:            UTF-8

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Tom George
tagline:             'They told me I should have a blog'
description:         'Welcome to my blog! Sometimes I write about programming.  I&#8217;ll also be using this to document stuff I learn, instead of stashing it away in a text file somewhere.  If the posts aren&#8217;t super fleshed-out, I apologize.  This blog is made with the <a href="https://github.com/poole/lanyon">Lanyon</a> theme for <a href="jekyllrb.com">Jekyll</a>.  I can be reached at <a href="mailto:tg82490@gmail.com">tg82490@gmail.com</a> or <a href="mailto:tgeorge@paychex.com">tgeorge@paychex.com</a>'
url:                 http://tomgeorge.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tom George
  url:               https://twitter.com/RealTomGeorge
  email:             tg82490@gmail.com

# Custom vars
version:             2.0.0
